<?php
/**
 * @file
 * Exposes other Database tables to Views.
 */

/**
 * Implements hook_config_info().
 */
function views_expose_tables_config_info() {
  $prefixes['views_expose_tables.settings'] = array(
    'label' => t('Views Expose Tables'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function views_expose_tables_menu() {
  $items['admin/structure/views/expose_tables'] = array( 
   'title' => 'Views Expose Tables', 
   'description' => 'Configuration for the Views Expose Table module.', 
   'page callback' => 'backdrop_get_form',
   'page arguments' => array('views_expose_tables_admin_form'), 
   'access arguments' => array('administer site configuration'),
   'type' => MENU_NORMAL_ITEM, 
	);

  return $items;
}

/** 
 * Page callback for admin form.
 */
function views_expose_tables_admin_form($form, &$form_state) {
  global $databases;
  $db = $databases['default']['default']['database'];

  $result = db_query("SHOW TABLES");
  if (!$result) {
    backdrop_set_message('Unable to access MySQL tables.', 'error');
  }

  if ($result->rowCount()) {
    while ($row = $result->fetchObject()) {
		  $tables[] = $row->{'Tables_in_' . $db};
    }
  }

  $options =  array();
  foreach ($tables as $table) {
    $options[$table] = $table;
  }

  $config = config('views_expose_tables.settings');
  $form['#config'] = 'views_expose_tables.settings';
  $form['expose_tables'] = array(
   '#type' => 'checkboxes',
   '#options' => $options,
   '#title' => t('Tables to expose as raw data to views'),
   '#description' => t('Check the tables to expose to views as base tables'),
   '#default_value' => $config->get('expose_tables'),
  );
  if (!$result) {
    $form['expose_tables']['disabled'] = TRUE;
  }

  $form['#submit'][] = 'views_expose_tables_admin_form_submit';

  return system_settings_form($form);

}

/** 
 * Submit handler for Views Expose Table admin config page
 *
 * @see views_expose_tables_admin_form().
 */
function views_expose_tables_admin_form_submit($form, &$form_state) {
  // Clear views cache, not views data cache.
  cache_clear_all('*', 'cache_views', TRUE);
}

/**
 * Implements hook_views_api().
 */
function views_expose_tables_views_api() {
  return array(
    'api' => 3,
    'path' => backdrop_get_path('module', 'views_expose_tables'),
  );
}
